name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use the latest LTS version

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm ci # `npm ci` is optimized for CI environments

      # Step 4: Build the React app
      - name: Build React App
        run: npm run build

      # Step 5: Deploy the app to the server
      - name: Deploy React App
        run: |
          # Define the source and target directories
          SOURCE_DIR="${GITHUB_WORKSPACE}/build"
          TARGET_DIR="/home/deployer/actions-runner-front/_work/paktyping-frontend/paktyping-frontend/build"

          # Ensure the target directory exists
          sudo mkdir -p $TARGET_DIR

          # Remove old build files
          sudo rm -rf $TARGET_DIR/*

          # Copy the new build files to the target directory
          sudo cp -r $SOURCE_DIR/* $TARGET_DIR/

          # Adjust permissions for Nginx
          sudo chmod -R 755 $TARGET_DIR
          sudo chown -R www-data:www-data $TARGET_DIR

          # Reeload Nginx to apply changes
          sudo systemctl reload nginx
